import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Sans_JP } from 'next/font/google'
import Footer from '@/components/Footer'

const plexjp = IBM_Plex_Sans_JP({ weight: ["100", "200", "300", "400", "500", "600", "700"], preload: false })

export const metadata: Metadata = {
  title: 'ab2m.link',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" data-theme="myTheme">
      <body className={`${plexjp.className} flex flex-col h-screen justify-between`}>
        <Navbar />
        <div className="mb-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
